name: grocery
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"   # TEMP so Zapp can import

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.6           # TEMP (Dart 2 compatible)
  cached_network_image: ^3.2.3  # TEMP
  form_field_validator: ^1.1.0
  animations: ^2.0.7            # TEMP (Dart 2 compatible)
  flutter_credit_card: ^3.0.2   # TEMP (safer for Dart 2)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3         # TEMP (Dart 2 compatible)
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.12.0  # TEMP (Dart 2 compatible)

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo_splash.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
